name:                hermit
version:             0.1.0.0
github:              "aitorres/hermit"
license:             MIT
author:              "Andrés Ignacio Torres"
maintainer:          "dev@aitorres.com"
copyright:           "2021 Andrés Ignacio Torres"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/aitorres/hermit#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  hermit-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hermit

tests:
  hermit-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hermit
