name: Haskell CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Stack
      run: curl -sSL https://get.haskellstack.org/ | sh
    - name: Build project
      run: stack build
    - name: Run tests
      run: stack test
